---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bcf24-tm-ns
  name: registration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: 863518452741.dkr.ecr.ap-south-1.amazonaws.com/bcf24/registration:latest
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: registration-service-app-settings
          env:
            - name: DATABASES
              valueFrom:
                secretKeyRef:
                  name: registration-service-db-settings
                  key: registration-service.json
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: bcf24-tm-ns
  name: registration-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
  selector:
    app: registration
---
apiVersion: autoscaling/v1  
kind: HorizontalPodAutoscaler
metadata:
  namespace: bcf24-tm-ns
  name: registration-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: registration-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 85  