---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bcf24-tm-ns
  name: ticket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: 863518452741.dkr.ecr.ap-south-1.amazonaws.com/bcf24/ticket:latest
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: ticket-service-app-settings
          env:
            - name: DATABASES
              valueFrom:
                secretKeyRef:
                  name: ticket-service-db-settings
                  key: ticket-service.json
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: bcf24-tm-ns
  name: ticket-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8002
      protocol: TCP
  selector:
    app: ticket
---
apiVersion: autoscaling/v1  
kind: HorizontalPodAutoscaler
metadata:
  namespace: bcf24-tm-ns
  name: ticket-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ticket-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 85   